# Generated by Django 2.1 on 2018-08-14 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='captain',
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.Group'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
    ]
