# Generated by Django 2.1 on 2018-08-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20180814_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_captain',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
