# Generated by Django 2.1 on 2018-08-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20180814_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_number',
            field=models.CharField(max_length=10),
        ),
    ]
